/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppRoot {}
  interface MoneyComponent {
    'money': any;
    'submitted': boolean;
    'updateform': any;
  }
}

declare global {


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMoneyComponentElement extends Components.MoneyComponent, HTMLStencilElement {}
  var HTMLMoneyComponentElement: {
    prototype: HTMLMoneyComponentElement;
    new (): HTMLMoneyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'money-component': HTMLMoneyComponentElement;
  }
}

declare namespace LocalJSX {
  interface AppRoot {}
  interface MoneyComponent {
    'money'?: any;
    'submitted'?: boolean;
    'updateform'?: any;
  }

  interface IntrinsicElements {
    'app-root': AppRoot;
    'money-component': MoneyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'money-component': LocalJSX.MoneyComponent & JSXBase.HTMLAttributes<HTMLMoneyComponentElement>;
    }
  }
}


